name: Automatic trigger draft release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  call-workflow-build-artifacts-and-run-tests:
    uses: ./.github/workflows/build-artifacts-and-run-tests.yml

  automated-draft-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: call-workflow-build-artifacts-and-run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Fetch
        uses: actions/download-artifact@v7
        with:
          path: artifacts

      - name: list all downloaded artifacts
        run: |
          tree artifacts/
          echo THIS WAS artifacts/

      - name: Organize Artifacts
        run: |
          # Create a directory for the final binaries
          mkdir -p target/release-binaries

          # Loop through each artifact subdirectory
          for artifact_dir in artifacts/*/; do
            # Get the platform name from the directory name
            platform=$(basename $artifact_dir)

            # Move and rename the file(s) inside the subdirectory
            for file in $artifact_dir/*; do
              filename=$(basename $file)

              # Check if the file has an extension
              if [[ "$filename" == *.* ]]; then
                extension="${filename##*.}" # Extract file extension
                new_name="$platform.$extension"
              else
                new_name="$platform" # No extension, use platform name as the filename
              fi

              # Move and rename the file
              mv "$file" "target/release-binaries/$new_name"
            done

            # Remove the now-empty subdirectory
            rmdir $artifact_dir
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: target/release-binaries/*
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}

      - name: Publish to crates.io
        shell: bash
        run: |
          ls -la
          git status
          version="v$(grep version Cargo.toml | head -n1 | cut -d '"' -f2)"
          git_tag="$(basename ${{ github.ref }})"
          echo "::notice::Cargo.toml version is: '$version', github tag is: '$git_tag'"
          if [ "$version" == "$git_tag" ]; then
            cargo publish --token "${{ secrets.CRATESIO_TOKEN }}" --verbose
          else
            echo "::warning title=Version mismatch::they don't match, not uploading!"
          fi
